### ISSUE TITLE
puppet version 3.7.2 installation not working for ubuntu/xenial64

### ISSUE THREAD

**Issue by kirean** [petems/puppet-install-shell#110]
with:

config.vm.box = "ubuntu/xenial64"

and

config.puppet_install.puppet_version = "3.7.2"

I got:

```
==> default: 13:56:30 +0000 INFO: 2.7.* Puppet deb package tied to Facter < 2.0.0, specifying Facter 1.7.4
==> default: Reading package lists...

==> default: Building dependency tree...
==> default: 
==> default: Reading state information...
==> default: E: Version '3.7.2-1puppetlabs1' for 'puppet-common' was not found
==> default: E: Version '3.7.2-1puppetlabs1' for 'puppet' was not found
==> default: E: Version '1.7.4-1puppetlabs1' for 'facter' was not found
==> default: 13:56:30 +0000 CRIT: Installation failed
==> default: 13:56:30 +0000 CRIT: Please file a bug report at https://github.com/petems/puppet-install-shell/
==> default: 13:56:30 +0000 CRIT: 
==> default: 13:56:30 +0000 CRIT: Version: 3.7.2
==> default: 13:56:30 +0000 CRIT: Platform: ubuntu
==> default: 13:56:30 +0000 CRIT: Platform Version: 16.04
==> default: 13:56:30 +0000 CRIT: Machine: x86_64
==> default: 13:56:30 +0000 CRIT: OS: Linux
==> default: 13:56:30 +0000 CRIT: 
==> default: 13:56:30 +0000 CRIT: Please detail your operating system type, version and any other relevant details
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sh install.sh -v 3.7.2 2>&1

Stdout from the command:

13:56:10 +0000 INFO: Version parameter defined: 3.7.2
13:56:10 +0000 INFO: Downloading Puppet 3.7.2 for ubuntu...
13:56:10 +0000 INFO: Ubuntu platform! Lets get you a DEB...
13:56:10 +0000 WARN: Puppet only offers Puppet 4 packages for Xenial, so only 3.7.2 package avaliable
13:56:10 +0000 WARN: Skipping download of Puppet repistory, using distro upstream instead
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security/main Sources [99.1 kB]
Get:6 http://security.ubuntu.com/ubuntu xenial-security/restricted Sources [2,600 B]
Get:7 http://archive.ubuntu.com/ubuntu xenial/main Sources [868 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [43.9 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/multiverse Sources [1,140 B]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [381 kB]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [168 kB]
Get:12 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [177 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial/restricted Sources [4,808 B]
Get:14 http://archive.ubuntu.com/ubuntu xenial/universe Sources [7,728 kB]
Get:15 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [94.0 kB]
Get:16 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3,208 B]
Get:17 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [1,336 B]
Get:18 http://archive.ubuntu.com/ubuntu xenial/multiverse Sources [179 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [7,532 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial/universe Translation-en [4,354 kB]
Get:21 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [144 kB]
Get:22 http://archive.ubuntu.com/ubuntu xenial/multiverse Translation-en [106 kB]
Get:23 http://archive.ubuntu.com/ubuntu xenial-updates/main Sources [280 kB]
Get:24 http://archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [3,404 B]
Get:25 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [177 kB]
Get:26 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Sources [7,592 B]
Get:27 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [652 kB]
Get:28 http://archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [273 kB]
Get:29 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [543 kB]
Get:30 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [221 kB]
Get:31 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.2 kB]
Get:32 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [7,996 B]
Get:33 http://archive.ubuntu.com/ubuntu xenial-backports/main Sources [3,432 B]
Get:34 http://archive.ubuntu.com/ubuntu xenial-backports/universe Sources [4,376 B]
Get:35 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [4,860 B]
Get:36 http://archive.ubuntu.com/ubuntu xenial-backports/main Translation-en [3,220 B]
Get:37 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [5,896 B]
Get:38 http://archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [3,060 B]
Fetched 24.4 MB in 16s (1,437 kB/s)
Reading package lists...
13:56:30 +0000 INFO: 2.7.* Puppet deb package tied to Facter < 2.0.0, specifying Facter 1.7.4
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '3.7.2-1puppetlabs1' for 'puppet-common' was not found
E: Version '3.7.2-1puppetlabs1' for 'puppet' was not found
E: Version '1.7.4-1puppetlabs1' for 'facter' was not found
13:56:30 +0000 CRIT: Installation failed
13:56:30 +0000 CRIT: Please file a bug report at https://github.com/petems/puppet-install-shell/
13:56:30 +0000 CRIT: 
13:56:30 +0000 CRIT: Version: 3.7.2
13:56:30 +0000 CRIT: Platform: ubuntu
13:56:30 +0000 CRIT: Platform Version: 16.04
13:56:30 +0000 CRIT: Machine: x86_64
13:56:30 +0000 CRIT: OS: Linux
13:56:30 +0000 CRIT: 
13:56:30 +0000 CRIT: Please detail your operating system type, version and any other relevant details


Stderr from the command:


```

**Comment by kirean** [comment]
I did a manual apt install on the box and got 3.8.5 installed.

**Comment by petems** [comment]
Hi @kirean! 3.7.2 is EOL, is there a reason you're picking that version?

**Comment by kirean** [comment]
I tried 3.8.5 first but then the plugin said it could only install 3.7.2. Rebuilding the machine so I can get the full error message for that try.

**Comment by kirean** [comment]
`==> default: 14:44:16 +0000 INFO: 2.7.* Puppet deb package tied to Facter < 2.0.0, specifying Facter 1.7.4
==> default: Reading package lists...

==> default: Building dependency tree...
==> default: 
==> default: Reading state information...

==> default: E: Version '3.8.5-1puppetlabs1' for 'puppet-common' was not found
==> default: E: Version '3.8.5-1puppetlabs1' for 'puppet' was not found
==> default: E: Version '1.7.4-1puppetlabs1' for 'facter' was not found
==> default: 14:44:17 +0000 CRIT: Installation failed
==> default: 14:44:17 +0000 CRIT: Please file a bug report at https://github.com/petems/puppet-install-shell/
==> default: 14:44:17 +0000 CRIT: 
==> default: 14:44:17 +0000 CRIT: Version: 3.8.5
==> default: 14:44:17 +0000 CRIT: Platform: ubuntu
==> default: 14:44:17 +0000 CRIT: Platform Version: 16.04
==> default: 14:44:17 +0000 CRIT: Machine: x86_64
==> default: 14:44:17 +0000 CRIT: OS: Linux
==> default: 14:44:17 +0000 CRIT: 
==> default: 14:44:17 +0000 CRIT: Please detail your operating system type, version and any other relevant details
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sh install.sh -v 3.8.5 2>&1

Stdout from the command:

14:43:57 +0000 INFO: Version parameter defined: 3.8.5
14:43:57 +0000 INFO: Downloading Puppet 3.8.5 for ubuntu...
14:43:57 +0000 INFO: Ubuntu platform! Lets get you a DEB...
14:43:57 +0000 WARN: Puppet only offers Puppet 4 packages for Xenial, so only 3.7.2 package avaliable
14:43:57 +0000 WARN: Skipping download of Puppet repistory, using distro upstream instead
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security/main Sources [99.1 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial/main Sources [868 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/restricted Sources [2,600 B]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [43.9 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/multiverse Sources [1,140 B]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [381 kB]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [168 kB]
Get:12 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [177 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial/restricted Sources [4,808 B]
Get:14 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [94.0 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial/universe Sources [7,728 kB]
Get:16 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3,208 B]
Get:17 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [1,336 B]
Get:18 http://archive.ubuntu.com/ubuntu xenial/multiverse Sources [179 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [7,532 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial/universe Translation-en [4,354 kB]
Get:21 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [144 kB]
Get:22 http://archive.ubuntu.com/ubuntu xenial/multiverse Translation-en [106 kB]
Get:23 http://archive.ubuntu.com/ubuntu xenial-updates/main Sources [280 kB]
Get:24 http://archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [3,404 B]
Get:25 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [177 kB]
Get:26 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Sources [7,592 B]
Get:27 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [652 kB]
Get:28 http://archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [273 kB]
Get:29 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [543 kB]
Get:30 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [221 kB]
Get:31 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.2 kB]
Get:32 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [7,996 B]
Get:33 http://archive.ubuntu.com/ubuntu xenial-backports/main Sources [3,432 B]
Get:34 http://archive.ubuntu.com/ubuntu xenial-backports/universe Sources [4,376 B]
Get:35 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [4,860 B]
Get:36 http://archive.ubuntu.com/ubuntu xenial-backports/main Translation-en [3,220 B]
Get:37 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [5,896 B]
Get:38 http://archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [3,060 B]
Fetched 24.4 MB in 16s (1,444 kB/s)
Reading package lists...
14:44:16 +0000 INFO: 2.7.* Puppet deb package tied to Facter < 2.0.0, specifying Facter 1.7.4
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '3.8.5-1puppetlabs1' for 'puppet-common' was not found
E: Version '3.8.5-1puppetlabs1' for 'puppet' was not found
E: Version '1.7.4-1puppetlabs1' for 'facter' was not found
14:44:17 +0000 CRIT: Installation failed
14:44:17 +0000 CRIT: Please file a bug report at https://github.com/petems/puppet-install-shell/
14:44:17 +0000 CRIT: 
14:44:17 +0000 CRIT: Version: 3.8.5
14:44:17 +0000 CRIT: Platform: ubuntu
14:44:17 +0000 CRIT: Platform Version: 16.04
14:44:17 +0000 CRIT: Machine: x86_64
14:44:17 +0000 CRIT: OS: Linux
14:44:17 +0000 CRIT: 
14:44:17 +0000 CRIT: Please detail your operating system type, version and any other relevant details


Stderr from the command:
`

**Comment by petems** [comment]
Sorry, I should have been more specific of the entirety Puppet 3.X is end of life, so there's no Puppet package for Xenial from the Puppetlabs upstream. Puppet 4 and 5 are now out.

Can you try installing with :latest instead?

**Comment by kirean** [comment]
latest (5.3.2) installed without problems.
