### ISSUE TITLE
ubuntu 12.04

### ISSUE THREAD

**Issue by Koma-Andrea** [petems/puppet-install-shell#111]
Hi, ubuntu 12.04 has only 1.10.0 as puppet-agent version for 4.10.*
these mean that cabling the 1.10.8-1precise is actually wrong.
can we use a :latest or :pc1 as tag to install the latest pc1 version?
looks more simpler

**Comment by petems** [comment]
Ubuntu 12.04 has been EOL since April 28, 2017, closing
