### ISSUE TITLE
Puppet repo structures changed

### ISSUE THREAD

**Issue by oren-shoemaker** [petems/puppet-install-shell#122]
Per https://groups.google.com/forum/#!topic/puppet-users/cCsGWKunBe4, some of the puppet repo structures have changed. Looks like the rpms structured as puppetX-release-<osfamily>-<version>.noarch.rpm have been moved up one folder level to http://yum.puppetlabs.com/ instead of http://yum.puppetlabs.com/puppetX.

**Comment by myanaros** [comment]
For Centos 7 Puppet 4 installs
`http://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm` Old URL
`http://yum.puppetlabs.com/puppet-release-el-7.noarch.rpm`seemingly New URL

**Comment by jnathlich** [comment]
18:37:03 +0000 INFO: Downloading http://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
18:37:03 +0000 INFO:   to file /tmp/install.sh.10723.random_hexdump/puppetlabs-release-pc1-el-6.noarch.rpm
18:37:03 +0000 INFO: Trying wget...
18:37:04 +0000 CRIT: ERROR 404
18:37:04 +0000 CRIT: Unable to retrieve a valid package!
18:37:04 +0000 CRIT: Please file a bug report at https://github.com/petems/puppet-install-shell/

Browsing directly to the rpm gets you this:
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: puppetlabs-release-pc1-el-6.noarch.rpm
RequestId: A73F33BD8E4A8053
HostId: BZJjobwS+T+terG+aMvPB4z0I82keJC/2cr9f3TR/xQZoTg/lynqbe8X/MzzSz0HfZjEnbGdTl8=

**Comment by jnathlich** [comment]
Ah, just read the issue below.  Puppet 4 EOL, so this was rather intentionally broken by Puppet.  Nevermind!

**Comment by petems** [comment]
Ok, reopening as they're going to add repos back:

```
s you may have seen, the packages we removed from {yum,apt}.puppetlabs.com this week have been put back. This was due to an outage and the need to restore from backups.

While we originally did not intend to enable repositories on release-archives.puppet.com, the overwhelming demand has made this a priority for us. We will keep the EOL packages on {yum,apt}.puppetlabs.com until that work is done, but then they will be re-archived. You can follow along here: https://tickets.puppetlabs.com/browse/CPR-685

To provide some clarity:
*The puppetlabs-release-* repos contain puppet 3 packages. THESE WILL BE ARCHIVED. You will soon be able to find them at http://release-archives.puppet.com/yum/puppet-archives-release-*.
*The puppetlabs-release-pc1-* repos contain puppet 4 packages. THESE WILL BE ARCHIVED. You will soon be able to find them at http://release-archives.puppet.com/yum/puppetlabs-release-pc1-*.
*puppet-release-* is our rolling repository, which always points to our latest software stream. This is currently puppet 6.
If you have any questions, please feel free to reach out.

Thanks!
```

**Comment by jnathlich** [comment]
Excellent.  This should fix our short-term issue.  Long term we just need to upgrade from puppet 4.
