### ISSUE TITLE
Missing download tool in latest docker images

### ISSUE THREAD

**Issue by Xenion1987** [petems/puppet-install-shell#145]
Related to the failed actions:
https://github.com/petems/puppet-install-shell/actions/runs/3116859742/jobs/5055060160#step:4:10
https://github.com/petems/puppet-install-shell/actions/runs/3116859742/jobs/5055060196#step:4:10

The docker images `ubuntu:latest` and `debian:latest` does not have installed any of the necessary tools to download the package.
As marked in the screenshot below, the script says `Trying perl...`, so `wget`, `curl` and `fetch` has already been skipped or failed [(1).](https://github.com/petems/puppet-install-shell/blob/master/install_puppet_6_agent.sh#L399-L423)

This issue can be fixed by installing one of them manually.

![grafik](https://user-images.githubusercontent.com/39803750/193357674-21b775f0-8b11-4785-b913-41b4b599e3bb.png)

Additional validation:
![grafik](https://user-images.githubusercontent.com/39803750/193358632-b0a43b12-ad5c-48bd-acb8-b3a99c691263.png)

**Comment by petems** [comment]
Hmm, so I guess the default perl code doesn't work... well, I can just add `apt-get install wget curl && yum install wget curl` or something like that to fix it

**Comment by xenion1987** [comment]
> I can just add `apt-get install wget curl && yum install wget curl` or something like that to fix it

I wanted to add that now, at least for the github actions.
In the script a clear hint would probably also suffice, so that the person who wants to use this script can choose for himself which program should be installed.

Another step for installing `curl `and/or `wget `would do the job for the Github actions.

**Comment by xenion1987** [comment]
I guess this issue can be closed since my last PR.
The mentioned action was successful, now:
https://github.com/petems/puppet-install-shell/actions/runs/3161934248

Though, this could still be helpful:
> In the script a clear hint would probably also suffice, so that the person who wants to use this script can choose for himself which program should be installed.
