### ISSUE TITLE
By default do not install puppet agent on ubuntu. Make it an option

### ISSUE THREAD

**Issue by wernerb** [petems/puppet-install-shell#22]
A constant running puppet agent started by default for ubuntu can be a pain for masterless users. We make masterless the standard, but make masterfull installations an option.
How does the '-a' (for agent) flag sound?

**Comment by petems** [comment]
This is a bit out of scope for the install stript IMO, this is something that's specific to the way that Debian flavour machines do things.

Something like setting the deny in `/usr/sbin/policy-rc.d` as detailed in https://major.io/2014/06/26/install-debian-packages-without-starting-daemons/
