### ISSUE TITLE
setup fails on fedora 21 due to missing packages

### ISSUE THREAD

**Issue by jhoblitt** [petems/puppet-install-shell#39]
It appears that the fedora 21 repos were reindexed about half an hour ago and all of the fedora 21 packages were removed.  While not an actual issue with the install script, others might run into this problem.

http://yum.puppetlabs.com/fedora/f21/products/x86_64/
```
[DIR]	Parent Directory	 	- 	 
[ ]	puppetlabs-release-21-11.noarch.rpm	29-Jan-2015 09:26 	14K	 
[DIR]	repodata/	30-Mar-2015 16:12 	- 	 
```
23:40:27 +0000 INFO: Version parameter defined: 3.7.5
23:40:27 +0000 INFO: Downloading Puppet 3.7.5 for fedora...
23:40:27 +0000 INFO: Fedora platform! Lets get the RPM...
23:40:27 +0000 INFO: Downloading http://yum.puppetlabs.com/fedora/f21/products/x86_64/puppetlabs-release-21-11.noarch.rpm
23:40:27 +0000 INFO:   to file /tmp/install.sh.2244.33831/puppetlabs-release-21-11.noarch.rpm
23:40:27 +0000 INFO: Trying wget...
23:40:27 +0000 INFO: installing puppetlabs yum repo with rpm...
warning: /tmp/install.sh.2244.33831/puppetlabs-release-21-11.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 4bd6ec30: NOKEY
Preparing...                          ########################################
Updating / installing...
puppetlabs-release-21-11              ########################################
No package puppet-3.7.5 available.
Error: Nothing to do
23:40:30 +0000 CRIT: Installation failed
23:40:30 +0000 CRIT: Please file a bug report at https://github.com/petems/puppet-install-shell/
23:40:30 +0000 CRIT: 
23:40:30 +0000 CRIT: Version: 3.7.5
23:40:30 +0000 CRIT: Platform: fedora
23:40:30 +0000 CRIT: Platform Version: 21
23:40:30 +0000 CRIT: Machine: x86_64
23:40:30 +0000 CRIT: OS: Linux
23:40:30 +0000 CRIT: 
23:40:30 +0000 CRIT: Please detail your operating system type, version and any other relevant details
```

**Comment by petems** [comment]
Yeah, looks like a temporary issue from the repo side, all working now! :+1:
