### ISSUE TITLE
Puppet 4.5?

### ISSUE THREAD

**Issue by ITler** [petems/puppet-install-shell#55]
I've restored a snapshot of a dev vagrant box and puppet upgrade didn't work. 
I use `vagrant-puppet-install 4.1.0`.   
As requested in error output, I file an issue here.

    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!

    sh install.sh -v 4.5.0 2>&1

    Stdout from the command:

    08:41:35 +0000 INFO: Version parameter defined: 4.5.0
    08:41:35 +0000 INFO: Matching Puppet version to puppet-agent package version (See http://docs.puppetlabs.com/puppet/latest/reference/about_agent.html for more details)
    08:41:35 +0000 CRIT: Unable to match requested puppet version to puppet-agent version - Check http://docs.puppetlabs.com/puppet/latest/reference/about_agent.html
    08:41:35 +0000 CRIT: Please file a bug report at https://github.com/petems/puppet-install-shell/
    08:41:35 +0000 CRIT: 
    08:41:35 +0000 CRIT: Version: 4.5.0
    08:41:35 +0000 CRIT: Platform: ubuntu
    08:41:35 +0000 CRIT: Platform Version: 14.04
    08:41:35 +0000 CRIT: Machine: x86_64
    08:41:35 +0000 CRIT: OS: Linux
    08:41:35 +0000 CRIT: 
    08:41:35 +0000 CRIT: Please detail your operating system type, version and any other relevant details

**Comment by ITler** [comment]
Nice, thanks!

**Comment by ITler** [comment]
Is it correct, that the merge wasn't built, yet? However `vagrant plugin update` did not update anything and `vagrant plugin list` still shows `vagrant-puppet-install (4.1.0)`

hell yeah. There is puppet 4.5.1 available now.

However while vagrant try upgrading an existing puppet installation within a box, it fails, because `apt-get install` requests user input. It asks how to handle existing config file.

    sh install.sh -v 4.5.1 2>&1
    [...]
    Configuration file '/etc/puppetlabs/puppet/puppet.conf'
    ==> Modified (by you or by a script) since installation.
    ==> Package distributor has shipped an updated version.
      What would you like to do about it ?  Your options are:
       Y or I  : install the package maintainer's version
       N or O  : keep your currently-installed version
         D     : show the differences between the versions
         Z     : start a shell to examine the situation
    The default action is to keep your current version.
    *** puppet.conf (Y/I/N/O/D/Z) [default=N] ?

I assume, this could be solved by using `apt-get -y install`?

**Comment by petems** [comment]
`apt-get install -y puppet-agent` is already used, for config override I believe it's `DEBIAN_FRONTEND=noninteractive` or `-o Dpkg::Options::="--force-confnew" `? Can you try one of those and I can add it to the script
