### ISSUE TITLE
Fails trying to find the right package

### ISSUE THREAD

**Issue by bitbandit** [petems/puppet-install-shell#68]
Hi, I'm trying to use the vagrant plugin and get the following error on vagrant up.  I'm guessing it's because my box is Ubuntu 16.10 Yakkety, which is not available here: https://apt.puppetlabs.com/
Is there a way to override and get Xenial instead, for example?  And is that advisable, or should I downgrade my box to Xenial?  (Note: this is a desktop box, not a server).

```
sh install.sh -v 4.8.1 2>&1

Stdout from the command:

16:05:47 -0500 INFO: Version parameter defined: 4.8.1
16:05:47 -0500 INFO: Matching Puppet version to puppet-agent package version (See http://docs.puppetlabs.com/puppet/latest/reference/about_agent.html for more details)
16:05:47 -0500 INFO: Downloading Puppet 4.8.1 for ubuntu...
16:05:47 -0500 INFO: Ubuntu platform! Lets get you a DEB...
16:05:47 -0500 INFO: Downloading http://apt.puppetlabs.com/puppetlabs-release-pc1-.deb
16:05:47 -0500 INFO:   to file /tmp/install.sh.1956.random_hexdump/puppetlabs-release-pc1-.deb
16:05:47 -0500 INFO: Trying wget...
16:05:47 -0500 CRIT: ERROR 404
16:05:47 -0500 CRIT: Unable to retrieve a valid package!
16:05:47 -0500 CRIT: Please file a bug report at https://github.com/petems/puppet-install-shell/
16:05:47 -0500 CRIT: 
16:05:47 -0500 CRIT: Version: 4.8.1
16:05:47 -0500 CRIT: Platform: ubuntu
16:05:47 -0500 CRIT: Platform Version: 16.10
16:05:47 -0500 CRIT: Machine: x86_64
16:05:47 -0500 CRIT: OS: Linux
```

**Comment by petems** [comment]
The packaging team generally doesnt make packages for the non LTS Ubuntu releases, so 

However, you could add something like this to your vagrant config to fix it, as Yakkety has Puppet in it's upstream so you can just run `apt-get install puppet-agent`

```
config.puppet_install.install_url = "https://git.io/vMWRo"
```

Can you test that works for you? 👍

**Comment by bitbandit** [comment]
Hey, thanks for responding so quickly!
I think it almost worked, but failed because of a user prompt:
```
Do you want to continue?
==> default:  [Y/n] 
==> default: Abort.
```

**Comment by petems** [comment]
Can you try this URL instead: https://git.io/vMWgd

**Comment by bitbandit** [comment]
Got it. I created my own gist URL with --assume-yes and that took care of it.  I assume -y is the same thing.  Sorry to bother you with that.  Thanks!
