### ISSUE TITLE
Add puppet5 support

### ISSUE THREAD

**Issue by attachmentgenie** [petems/puppet-install-shell#87]
puppet 5 cant be installed using the puppetlabs-release-pc1 packages but now requires the new puppet5-release-* packages.

Adding puppet5 support will require some significant rework of the existing install.sh, or would you consider  placing it in a seperate script?

**Comment by petems** [comment]
Hmm, let's keep with the previous convention and have a new script called `install_puppet_5_agent.sh` or something like that. Means we don't accidentally update someones Puppet to a major version or something.

**Comment by attachmentgenie** [comment]
i would agree, that would be the sensible thing to do and as a sidenote probably easier to do.

**Comment by petems** [comment]
Closed vis #89
